apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:    matchLabels:
      app: {{ .Release.Name }}  template:
    metadata:      labels:
        app: {{ .Release.Name }}    spec:
      {{- if .Values.imagePullSecrets }}      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        {{- if kindIs "string" . }}
        - name: {{ . }}        {{- else }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          {{- $cfg := (default dict .Values.config) -}}
          {{- if (and (hasKey $cfg "enabled") (index $cfg "enabled")) }}
          env:
            {{- $data := (default dict (index $cfg "data")) -}}
            {{- range $k, $v := $data }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          {{- end }}
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 8080
          #  initialDelaySeconds: 10
          #  periodSeconds: 10
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: 8080
          #  initialDelaySeconds: 20
          #  periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
